version: '3'

services:
  games_discount_promotions_service:
    build: .
    image: 3thr3n/games_discount_promotions_service:latest
    volumes:
      - ./db/lowdb/:/usr/src/games_service/db/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - ${PORT}:3000
    environment:
      # Basic
      - TZ=${TIMEZONE}
      - TIMEZONE=${TIMEZONE}
      - TIMEZONE_LOCALE=${TIMEZONE_LOCALE}
      - HOUR_12=${HOUR_12}
      - LOCALE=${LOCALE}
      - COUNTRY=${COUNTRY}
      - CRON=${CRON}
      - EXPIRE_THRESHOLD=${EXPIRE_THRESHOLD}
      # Telegram
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHATID=${TELEGRAM_CHATID}
      # Steam
      - STEAM_ENABLED=${STEAM_ENABLED}
      - STEAM_GAME_PRICE=${STEAM_GAME_PRICE}
      - STEAM_GAME_PERCENTAGE=${STEAM_GAME_PERCENTAGE}
      # Epic
      - EPIC_ENABLED=${EPIC_ENABLED}
      # GOG
      - GOG_ENABLED=${GOG_ENABLED}
      - GOG_CURRENCY=${GOG_CURRENCY}
      - GOG_GAME_PRICE=${GOG_GAME_PRICE}
      - GOG_GAME_PERCENTAGE=${GOG_GAME_PERCENTAGE}
      # Ubisoft
      - UBISOFT_ENABLED=${UBISOFT_ENABLED}
      - UBISOFT_GAME_PRICE=${UBISOFT_GAME_PRICE}
      - UBISOFT_GAME_PERCENTAGE=${UBISOFT_GAME_PERCENTAGE}
      # MongoDB
      - MONGO_ENABLED=${MONGO_ENABLED}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:5
    restart: unless-stopped
    volumes:
      - ./db/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
