name: Creating a working Docker-Image
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Building Docker-Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: 4
          token: ${{ secrets.GH_3THR3N_TOKEN }}
      
      # Get npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Update Version
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        id: bumpTag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_3THR3N_TOKEN }}
        with:
          minor-wording:  'feature,Feature'
          major-wording:  'MAJOR, major, Major'
          patch-wording:  'patch,fixes,bugfix,Patch,Fixes,Bugfix,fix,FIX,Fix'
          rc-wording: 'Release,RELEASE,release,rc,RC'
          tag-prefix:  'v'
        
      - name: Set up Docker Buildx
        if: steps.bumpTag.outputs.newTag == ''
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        if: steps.bumpTag.outputs.newTag == ''
        uses: docker/setup-qemu-action@v1

      - name: Login to DockerHub
        if: steps.bumpTag.outputs.newTag == ''
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: steps.bumpTag.outputs.newTag == ''
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: |
            3thr3n/games_discount_promotions_service:latest
            3thr3n/games_discount_promotions_service:${{ steps.bumpTag.outputs.newTag }}