name: Creating a working Docker-Image
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Building Docker-Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_3THR3N_TOKEN }}
      
      # Get npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Update Version
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording:  'feature,Feature'
          major-wording:  'MAJOR, major, Major'
          patch-wording:  'patch,fixes,bugfix,Patch,Fixes,Bugfix,fix,FIX,Fix'
          rc-wording: 'Release,RELEASE,release,rc,RC'
          tag-prefix:  'v'
          skip-push: true

      # Get tag which we just created
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v0.0.0 # Optional fallback tag to use when no tag can be found

      - name: Commit report
        run: |
          git config --global user.name '3thr3n'
          git config --global user.email '3thr3n@users.noreply.github.com'
          git push ${{ steps.previoustag.outputs.tag }}

      - name: Set up Docker Buildx
        if: ${{ steps.previoustag.outputs.tag != 'v0.0.0' }}
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        if: ${{ steps.previoustag.outputs.tag != 'v0.0.0' }}
        uses: docker/setup-qemu-action@v1

      - name: Login to DockerHub
        if: ${{ steps.previoustag.outputs.tag != 'v0.0.0' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: ${{ steps.previoustag.outputs.tag != 'v0.0.0' }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: |
            3thr3n/games_discount_promotions_service:latest
            3thr3n/games_discount_promotions_service:${{ steps.previoustag.outputs.tag }}