name: Pull Request Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.0.4
        if: always()
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: 'eslint_report.json'